#!/bin/bash
# This script generates
# * template files
# * news generation script
# * pages generation script
# of the site using AMLEO: http://opengamestudio.org/amleo
#
# NOTE Only run this script if you know what you're doing
#

DIR=`dirname $0`
SITE_GEN_STG=$DIR/../../site-generator/stages
GEN=amleo.py

# 01.News
$GEN $DIR/01*/{cfg,t} $SITE_GEN_STG/0{1,2}*/v $DIR/01*/v
# 02.Pages.
#$GEN $STG/02*/{cfg,t} $STG/0{1,2}*/v
