#!/bin/bash

STAGE=$1

if [ -z "$STAGE" ];
then
    echo "Usage: $0 STAGE"
    exit 1
fi

DIR=`dirname $0`
DST="../$DIR"

# News templates.
cp $DIR/$STAGE/en.news*.html $DST/data/news-en
cp $DIR/$STAGE/ru.news*.html $DST/data/news-ru
# Page templates.
cp $DIR/$STAGE/en.page.html $DST/data/page-en
cp $DIR/$STAGE/ru.page.html $DST/data/page-ru

# Scripts.
cp $DIR/$STAGE/*.py $DST
